[theme]
base = "dark"
primaryColor = "#00C853"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2130"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
